### ISSUE TITLE
error: no custom builds generated

### ISSUE THREAD

**Issue by despecial** [foundation/node-foundation-customizer#32]
See this ticket here: https://github.com/foundation/foundation-sites/issues/12214

1.) Followed [these steps](https://github.com/foundation/node-foundation-customizer/blob/master/README.md#installing-dependencies)
- git clone git@github.com:zurb/node-foundation-customizer && cd node-foundation-customizer 
- npm install
- npm start

2.) page at localhost:3000/sites/download is up and running

3.) impossible to generate a custom build, results in a 404
```
Sun, 21 Mar 2021 17:47:33 GMT node-foundation-customizer:server ./node_modules/.bin/gulp customizer --modules /tmp/tmp.6.6.3.10520aeff36abf8d076549615c3f2f6c.json --output /tmp/tmp.6.6.3.10520aeff36abf8d076549615c3f2f6c
 
Sun, 21 Mar 2021 17:47:33 GMT node-foundation-customizer:server Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by DanielRuf** [comment]
Please try this:

```
npm i
npm run foundation
npm start
```

**Comment by despecial** [comment]
npm run foundation

that did that trick! thanks
